const basicUrl = "http://mobileapi.studyabroadapply.com/";
const baseAppUrl = basicUrl + "application/";
const Urls = {
  Login: basicUrl + "account/Login",
  HomeGraphs: basicUrl + "Home/GetGraphsData",
  BrowseApplications: baseAppUrl + "browseApplication",
  GetAppNotes: baseAppUrl + "GetApplicationNotes",
  GetApplicationStatus: baseAppUrl + "PopulateApplicationStatus",
  GetAppCompIds: baseAppUrl + "course",
  GetProfile: baseAppUrl + "PopulateProfile",
  GetDocs: baseAppUrl + "PopulateApplicationDocument",
  GetCountriesList: baseAppUrl + "GetCountryList",
  GetNationalityList: baseAppUrl + "GetNationality",
  GetCoursesList: baseAppUrl + "GetCourseList",
  GetCourseDisciplineList: baseAppUrl + "GetCourseDisciplineList",
  GetInstituteList: baseAppUrl + "GetInstituteList",
  GetLevelList: baseAppUrl + "GetLevelList",
  GetIntakeList: baseAppUrl + "GetIntakesList",
  UpdateAppStatus: baseAppUrl + "UpdateApplicationStatus",
  GetStatusList: baseAppUrl + "getApplicationStatusList",
  GetTravelInfo: baseAppUrl + "PopulateTravalInformation",
  SetNote: baseAppUrl + "InsertApplicationNotes",
  CreateProfile: baseAppUrl + "updateProfile",
  SearchCourse: basicUrl + "search/courseByName",
  GetCourseAutoFill: basicUrl + "search/courseAutoFill",
  GetDisciplineAutoFill: basicUrl + "search/CourseDisciplineAutoFill",
  CourseApply: basicUrl + "search/courseApply",
  CourseApplyApp: baseAppUrl + "courseApply",
  RegisterStudent: basicUrl + "account/signup",
  NotificationsList: baseAppUrl + "getApplicationNotificationList",
  DeleteNotification: baseAppUrl + "DeleteNotification",
  MarkAllNotificationAsRead: baseAppUrl + "MarkAllNotificationAsRead",
};

export default Urls;
